import { Context } from '@deepseek-ai/cordis'
import { Remote, TypertRemoteService } from '@deepseek-ai/dsh-typert-protocol'
import { defineDomain, domainTable, type Domain } from '@deepseek-ai/dsh-storage-domain'
import { z } from 'zod'
import { ActiveStateSchema, parseSkin, parseSkinText, SkinSchema, SkinSummarySchema, type ActiveState, type Skin, type SkinSummary } from './schema.js'

const domainSpec = defineDomain({ name: 'skin_studio', version: 1, global: { schema: ActiveStateSchema, initial: { activeId: null, revision: 0 } }, tables: { skins: domainTable(z.object({ skin: SkinSchema }).strict()) } })
type SkinRow = { skin: Skin }
const now = () => new Date().toISOString()
const safeId = (id: string) => { if (!/^[a-z0-9][a-z0-9-]{0,63}$/.test(id)) throw new Error('Invalid skin id.'); return id }

export class SkinStudioRemote extends TypertRemoteService {
  constructor(private readonly domain: Domain<typeof domainSpec>, ctx: Context) { super(ctx, 'skinStudio') }
  @Remote async list(): Promise<SkinSummary[]> { return [...this.domain.table('skins').entries()].map(([,row]) => SkinSummarySchema.parse({ id:row.skin.id,name:row.skin.name,description:row.skin.description,updatedAt:row.skin.updatedAt,source:row.skin.source })).sort((a,b) => b.updatedAt.localeCompare(a.updatedAt)) }
  @Remote async get(id: string): Promise<Skin | null> { return this.domain.table('skins').get(safeId(id))?.skin ?? null }
  @Remote async save(input: Skin): Promise<Skin> { const parsed=parseSkin(input); const existing=this.domain.table('skins').get(parsed.id)?.skin; const skin={...parsed,createdAt:existing?.createdAt ?? parsed.createdAt ?? now(),updatedAt:now()}; await this.domain.table('skins').put(skin.id,{skin}); return skin }
  @Remote async remove(id: string): Promise<boolean> { const key=safeId(id); const active=this.domain.global.get(); if(active.activeId===key) await this.domain.global.set({...active,activeId:null,revision:active.revision+1}); return this.domain.table('skins').delete(key) }
  @Remote async active(): Promise<ActiveState> { return this.domain.global.get() }
  @Remote async activate(id: string | null): Promise<ActiveState> { if(id !== null && !this.domain.table('skins').get(safeId(id))) throw new Error('Skin not found.'); const current=this.domain.global.get(), next={activeId:id,revision:current.revision+1}; await this.domain.global.set(next); return next }
  @Remote async import(text: string): Promise<Skin> { const skin=parseSkinText(text); if(this.domain.table('skins').get(skin.id))throw new Error(`Skin id already exists: ${skin.id}`); return this.save({...skin,source:'import'}) }
  @Remote async export(id: string): Promise<string> { const skin=await this.get(id); if(!skin) throw new Error('Skin not found.'); return JSON.stringify(skin,null,2) }
  @Remote async pluginSource(id: string): Promise<string> { const skin=await this.get(id); if(!skin) throw new Error('Skin not found.'); return `// Client entry generated by dsh-skin-studio. Bundle it as the dsh.client entry of a DSH npm package.\nexport const name = 'skin-${skin.id}'\nexport const inject = ['theme']\nexport function apply(ctx) {\n  return ctx.theme.overrideTokens('skin-${skin.id}', ${JSON.stringify(skin.tokens,null,2)})\n}\n` }
}
export async function openSkinStudio(ctx: Context): Promise<SkinStudioRemote> { const domain=await ctx.storageDomain.open(domainSpec); ctx.effect(() => () => domain.close()); return new SkinStudioRemote(domain,ctx) }
