/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ActiveState, Skin, SkinSummary } from 'dsh-skin-studio/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$736b696e53747564696f {
    activate: (id: string | null) => Promise<RemoteResult<ActiveState>>
    active: () => Promise<RemoteResult<ActiveState>>
    export: (id: string) => Promise<RemoteResult<string>>
    get: (id: string) => Promise<RemoteResult<Skin | null>>
    import: (text: string) => Promise<RemoteResult<Skin>>
    list: () => Promise<RemoteResult<SkinSummary[]>>
    pluginSource: (id: string) => Promise<RemoteResult<string>>
    remove: (id: string) => Promise<RemoteResult<boolean>>
    save: (input: Skin) => Promise<RemoteResult<Skin>>
  }
  interface TypertRemoteMap {
    'skinStudio/activate': (id: string | null) => Promise<RemoteResult<ActiveState>>
    'skinStudio/active': () => Promise<RemoteResult<ActiveState>>
    'skinStudio/export': (id: string) => Promise<RemoteResult<string>>
    'skinStudio/get': (id: string) => Promise<RemoteResult<Skin | null>>
    'skinStudio/import': (text: string) => Promise<RemoteResult<Skin>>
    'skinStudio/list': () => Promise<RemoteResult<SkinSummary[]>>
    'skinStudio/pluginSource': (id: string) => Promise<RemoteResult<string>>
    'skinStudio/remove': (id: string) => Promise<RemoteResult<boolean>>
    'skinStudio/save': (input: Skin) => Promise<RemoteResult<Skin>>
  }
  interface TypertRemoteNamespaceMap {
    'skinStudio': TypertRemoteNamespace$736b696e53747564696f
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
